<a href="https://colab.research.google.com/github/KomalMano/Story/blob/master/10_Support_Vector_Machine_(SVM)_code.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import pandas as pd
from sklearn.datasets import load_digits

In [5]:
digit = load_digits()

In [7]:
dir(digit)

['DESCR', 'data', 'images', 'target', 'target_names']

In [9]:
digit.data

array([[ 0.,  0.,  5., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ..., 10.,  0.,  0.],
       [ 0.,  0.,  0., ..., 16.,  9.,  0.],
       ...,
       [ 0.,  0.,  1., ...,  6.,  0.,  0.],
       [ 0.,  0.,  2., ..., 12.,  0.,  0.],
       [ 0.,  0., 10., ..., 12.,  1.,  0.]])

In [10]:
digit.target

array([0, 1, 2, ..., 8, 9, 8])

In [11]:
df = pd.DataFrame(digit.data)
df.head()

    0    1    2     3     4     5    6   ...   57   58    59    60    61   62   63
0  0.0  0.0  5.0  13.0   9.0   1.0  0.0  ...  0.0  6.0  13.0  10.0   0.0  0.0  0.0
1  0.0  0.0  0.0  12.0  13.0   5.0  0.0  ...  0.0  0.0  11.0  16.0  10.0  0.0  0.0
2  0.0  0.0  0.0   4.0  15.0  12.0  0.0  ...  0.0  0.0   3.0  11.0  16.0  9.0  0.0
3  0.0  0.0  7.0  15.0  13.0   1.0  0.0  ...  0.0  7.0  13.0  13.0   9.0  0.0  0.0
4  0.0  0.0  0.0   1.0  11.0   0.0  0.0  ...  0.0  0.0   2.0  16.0   4.0  0.0  0.0

[5 rows x 64 columns]

In [17]:
df['target'] = digit.target
df.head()

     0    1    2     3     4     5  ...    59    60    61   62   63  target
0  0.0  0.0  5.0  13.0   9.0   1.0  ...  13.0  10.0   0.0  0.0  0.0       0
1  0.0  0.0  0.0  12.0  13.0   5.0  ...  11.0  16.0  10.0  0.0  0.0       1
2  0.0  0.0  0.0   4.0  15.0  12.0  ...   3.0  11.0  16.0  9.0  0.0       2
3  0.0  0.0  7.0  15.0  13.0   1.0  ...  13.0  13.0   9.0  0.0  0.0       3
4  0.0  0.0  0.0   1.0  11.0   0.0  ...   2.0  16.0   4.0  0.0  0.0       4

[5 rows x 65 columns]

In [20]:
X = df.drop(['target'], axis='columns')
X.head()

    0    1    2     3     4     5    6   ...   57   58    59    60    61   62   63
0  0.0  0.0  5.0  13.0   9.0   1.0  0.0  ...  0.0  6.0  13.0  10.0   0.0  0.0  0.0
1  0.0  0.0  0.0  12.0  13.0   5.0  0.0  ...  0.0  0.0  11.0  16.0  10.0  0.0  0.0
2  0.0  0.0  0.0   4.0  15.0  12.0  0.0  ...  0.0  0.0   3.0  11.0  16.0  9.0  0.0
3  0.0  0.0  7.0  15.0  13.0   1.0  0.0  ...  0.0  7.0  13.0  13.0   9.0  0.0  0.0
4  0.0  0.0  0.0   1.0  11.0   0.0  0.0  ...  0.0  0.0   2.0  16.0   4.0  0.0  0.0

[5 rows x 64 columns]

In [22]:
y = df.target
y

0       0
1       1
2       2
3       3
4       4
       ..
1792    9
1793    0
1794    8
1795    9
1796    8
Name: target, Length: 1797, dtype: int64

In [23]:
import matplotlib.pyplot as plt
%matplotlib inline

In [ ]:
plt.xlabel('x axis')
plt.ylabel('y axis')
plt.scatter

In [24]:
from sklearn.model_selection import train_test_split

In [25]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2)
X_train,X_test,y_train,y_test

(       0    1     2     3     4     5   ...    58    59    60    61    62   63
 1121  0.0  0.0   4.0  13.0  16.0  16.0  ...   6.0  14.0   0.0   0.0   0.0  0.0
 1588  0.0  2.0  16.0  16.0  16.0  12.0  ...  16.0  16.0  13.0   1.0   0.0  0.0
 38    0.0  0.0   7.0   7.0  13.0  16.0  ...  11.0  16.0   6.0   0.0   0.0  0.0
 1363  0.0  0.0   2.0  16.0  14.0   2.0  ...   2.0  13.0  16.0  12.0   0.0  0.0
 1556  0.0  0.0   1.0  15.0  14.0   1.0  ...   2.0  16.0  11.0   0.0   0.0  0.0
 ...   ...  ...   ...   ...   ...   ...  ...   ...   ...   ...   ...   ...  ...
 1433  0.0  0.0   3.0  12.0  15.0  11.0  ...   2.0  13.0  16.0  12.0   0.0  0.0
 274   0.0  0.0   2.0  12.0  16.0  10.0  ...   3.0  13.0  16.0   3.0   0.0  0.0
 1176  0.0  0.0   8.0  16.0  10.0   2.0  ...   3.0  14.0  16.0  16.0  11.0  1.0
 1067  0.0  1.0  13.0  14.0   2.0   0.0  ...  12.0  14.0  13.0   6.0   0.0  0.0
 715   0.0  0.0   0.0   1.0   7.0  12.0  ...   0.0   0.0   8.0   6.0   0.0  0.0

 [1437 rows x 64 columns],
        0    1     2     3     4     5   ...    58    59    60    61    62   63
 1356  0.0  0.0   0.0  12.0  14.0   5.0  ...   1.0  10.0  14.0  15.0   2.0  0.0
 699   0.0  0.0   2.0  12.0  16.0  10.0  ...   1.0  12.0  16.0   5.0   0.0  0.0
 422   0.0  0.0  10.0  15.0   6.0   0.0  ...   9.0  16.0  13.0   4.0   0.0  0.0
 1762  0.0  0.0   2.0  13.0  13.0   1.0  ...   2.0  12.0  16.0  13.0   7.0  0.0
 420   0.0  0.0   1.0   9.0  14.0  11.0  ...   0.0   9.0  12.0   7.0   0.0  0.0
 ...   ...  ...   ...   ...   ...   ...  ...   ...   ...   ...   ...   ...  ...
 1115  0.0  0.0   1.0  13.0   2.0   0.0  ...   1.0  11.0  16.0  16.0  13.0  1.0
 1414  0.0  0.0  10.0   9.0  14.0  10.0  ...   9.0  16.0   7.0   0.0   0.0  0.0
 762   0.0  1.0   8.0  16.0  16.0   3.0  ...  12.0  16.0  12.0   3.0   0.0  0.0
 1779  0.0  0.0   3.0  10.0  16.0  16.0  ...   3.0  12.0   0.0   0.0   0.0  0.0
 592   0.0  0.0   0.0   6.0  14.0  10.0  ...   0.0   6.0  10.0  15.0  15.0  0.0

 [360 rows x 64 columns],
 1121    7
 1588    3
 38      8
 1363    8
 1556    1
        ..
 1433    8
 274     8
 1176    9
 1067    8
 715     9
 Name: target, Length: 1437, dtype: int64,
 1356    9
 699     8
 422     0
 1762    6
 420     6
        ..
 1115    6
 1414    8
 762     2
 1779    7
 592     8
 Name: target, Length: 360, dtype: int64)

In [26]:
len(X_train)

1437

In [27]:
len(X_test)

360

In [28]:
from sklearn.svm import SVC
model = SVC()

In [30]:
model.fit(X_train, y_train)

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='rbf',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

**Score**

In [32]:
model.score(X_test,y_test)

0.9916666666666667

**Tune Parameter**

**1.Regularization(C)**

In [33]:
model_C = SVC(C=1)
model_C.fit(X_train, y_train)
model_C.score(X_test, y_test)

0.9916666666666667

In [34]:
model_C = SVC(C=10)
model_C.fit(X_train, y_train)
model_C.score(X_test, y_test)

0.9944444444444445

**2.Gamma**

In [35]:
model_g = SVC(gamma=10)
model_g.fit(X_train, y_train)
model_g.score(X_test, y_test)

0.08055555555555556

**3.Kernel**

In [36]:
model_linear_kernel = SVC(kernel='linear')
model_linear_kernel.fit(X_train, y_train)
model_linear_kernel.score(X_test, y_test)

0.975

In [39]:
model_linear_kernel.score(X_test,y_test)

1.0